sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: lm9QwabnaoJmEskfEGJqcnf5R/0XNZXcg8YREYAcNLRgXBZzhp4pXB2QBcqw4rRf9CT7qdN3J67bBUZl/Nf6JbyaCTalbxy8pxXPUM+T3Gj0jgNSDIFIz0UuO3qKVDZkcXAOLXjjLc+8q1GleiBoIAgsTpkDmdQ9I2d493hcFa1EQLl3BPb/T7jLw2jKR50+Kud4b5RW7rsajNSYzdJ63AxwyAyUECwGBQtRujQ3nXrUYBNyK+7ZxtlEpsUomYX2/Q08U2pjNHNgAClNN674RycoAf/RXcTnjWrExWqqhn4sls7+XE3Np1xvq7P9lT5FlyCD4qrnl6XlwAsPByKCwNd3UWRCGc6HholhiMxMPXkiFOp5/Z1G+NrQAi7JR4tNj0KTQXmXDZpFq2rKjk7yV2iN/2jD6vLCE0rCnyJuBIH+HT3RaUqrfo53J2bENKEc0ML2Z4Kx4S0OWOkzZ/MP0AEdUEAU2SMNzMNS/SpaUDtdYPLnzTvmV9neRurFgLUtzNkMVAZz24nMpSfwnGs4Mqszn8fUbBPgdoYF8Hd1hkgjowsx55mdCFcJGQDitpPDAaStuc7NH6EGMsia7jsoU74aC2QaNYJnpZLcnTlVbG4Es7wmtAGheXhPORRg9hM15hIfuW7meqOX0d9ZYjvVOItnUY0LVJ5UseGuTSKjHL0=
  - secure: JcPOeohxZ/KNmhDc57OPNqudXVMgg2jOEJippH6Yl8WOxlj54KvRRvnVQsJXWvVk7KwEDIPXeFybSnNnyb5eo/K1XSUYlKzauckXBzerp0HaDvdIlXcr6/dOWIg8q2uhYhAMhTtEs5EE6y+wewt0dz2ZDgY+iRGwUHpzDdZo4kW/gCpQJ8j/Fud5pz39BPRFHh0Qw6whFjzqWbQqmoIyP7cic+XmXwQGtVkCjhLLnbvh8Idgf8yuEQWkctLYX7uBMHSL3VPgRiq3KF+0iskmbRtffNUKhwTldEnSnpZ4ZqSRjOMPI1KcMAvGcR66MzejgctF6fpyrPRiTJWKIgc6n5D6xZXFZYVQOtaZWg0fwgPKsFLAvgVX99BVLuwuurn9WmhipMG6VEwl+DhAvq421jPOV48lV9Qd7+ExKa9yUd2l63m5ZiTzjzX3ExfyOnh9+om0m5+W0PIrdYD95ea5F94ehixueQDQNarLQwiUVHnXsCCdOJJjMvSwK75Jsiw+tdc0TiprQXdET/AvDRT9WXdqN7Z+3w1+QN8v6hqgHPAJBlptQ9WLwJbaPdg26r+aTh1zpqzfPVP2GNiJYUFOPDczqahBbTB+DTG6G9X7ge+DmGwupEE+HNAGPmrKoXqhOc+7BXjzDH1SB2i7Ei4Q8syu8VhWzXQ2eZrQxCBLhYc=
