<<<<<<< HEAD
sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
- export TZ=Canada/Pacific
- date
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
    secure: Mo0ZsXHYwzP5rDR2ku38jFW8DxIeLsx4mvCanhFAwrhS/0Zj+sJYR+HcUvwryNSPfAlX/EvkYi4fxBVkDxrl8/C2kxOJMgKMvrfcYmOZsWibEPH+UDKcRrd4uol7JLcl2i01I2+RqyLuOszGb2jx/Iz+ekhHItkUs+hYidURna40TqtREU5Mt0HqXhm0ilfquGnrCqpjwcgu6IfTDmqxM7q8W/t0rpUvgNlDcLhAn8M3EQztVYyWKt8uAfCGerEJnRhVYk06ecMNdF0kzDnE95yHgnKF5DO/6DnS1hSF7hhFaMNqQpDo5TW0jdX7LvPF9s5Lta5kFPDpfZXUYDs5UkkQu10vcpVQMkMpMAMXWuOHBBWatMHsHrGwS2LsCARh/9DpB8UbhDLT1d8KBUZkA93OC/5Ow86WpTgZhCCR37MkKDxggAu/Uw8JzcI13wP1CWVuMpjKsxoLNMwCLUszAB1Ccdo06YXlvb6fhEGjDpnxN9Fs6MLqxoqHkBLqfD8c69ebTr3sY/KK1HJbJss8aFfVgWyI1rXmA7blJlH7ytaSeEwOOsJr+JuSgd3mtTnclrik4DWr/zNoZv9F1hxTHexg5CwUVG6BOyJhqwHwmVJ7uHdQlFicLYV+glCNtg4U2+zMh09Z09Egf4JZrHjGdByubZGliyT6tmJlG/ockTU=
    secure: JGDeWQlSjRsVOlwrH6TfyqBrnPFK2CNwWub8OFQQ7i3vOEkWEKx/J2644JU9F835CDoxygMNGGsG+CufF2JCF69UflYnWnxxrDxVCZHQ+BG7jYKX3bcgwnRJo/WVmzWDOhXApz9GxynedyxhlHLuhKJgnrNSExaWjTy8ERRBbXhIxUi8u7tTM5LrxQ/yOoxgIv/YbGfxxDfh2Mkl54aBbexl9RyQwaepv32YwQRayHYTZLgVoapRCoCWl8Ahk514byyfauAZWwNnh+vQRyS/0dRMWFSWiNLd5wSLdM/JIG2RUTSnlu35SvupMXphLoPdiQQy5/oQOCyKe8XGcQZwGeaDubjAHAo873x8zTUX3RJkbSttqmfMjnRbm5GA72ezGAiX3HlbsnKiSG/EsL5xhAJi5OiPkLbnu6nryQ6UmpvbQdWCAMjkJCrvTLdF7tyi7FbyQT3Rs1eUVnYJs6rNxD4gnR2cnxE36zO/MQE9MypnfJQHfLtOLHkMAoME2XVWLOWRQo6PmXixBh5tdz+XZuEqt6brG+jCc0ClWxfalPnK2I+6xkGCt5SZd3TuiOI195n1yyCA+eiiVHDs5v4zo8A/XQnmeMMixZZjoxGK6sa3l2UUFzKsVQS+00OumHQHGv7QXz2s+biLN6Nt2ombs5x5KkXLkdWNTTeUgS4/fWU=
